### ISSUE TITLE
Demo testing bugs

### ISSUE THREAD

**Issue by laemtl** [aces/EEG2BIDS#35]
- [x] errors are not displayed on the popup (ex: {'error': ['The LORIS SiteID is missing.', 'The LORIS ProjectID is missing.', 'The LORIS SubProjectID is missing.', 'The LORIS Visit Label is missing.']}
  - to reproduce: run tasks with an empty visit, session, project, site or powerline freq. 
- [x] default modality isn't stored - user has to click the EEG/iEEG radio to get a modality selected
- [x] EDF files without an Annotations channel were failing. File failing if it didn't come with events embedded in the last channel (the script is assuming an events.tsv inside the generated BIDS folder)
- [x] file extension ending in .EDF (caps) not recognized. 
- [x] test the corner cases (no output dir, no selected modality, no events file)
- [x] Events.tsv should be optional
- [x] iEEG should say Stereo iEEG
also see errors spotted last week, below (which Alizee hasn't had time to fix).

**Comment by christinerogers** [comment]
adding cecile's additional comments from slack: 

where do you enter the subject ID? I did not find it anywhere. (this is round 2) 

where do you enter the task name? I did not find it anywhere either (will have to be round 2)

**Comment by christinerogers** [comment]
adding here too points from round 1 (email friday) 
- MNE-BIDS should be mentioned e.g Welcome tab ""Powered by open source software and MNE-BIDS" 
- "Power"line frequency: n/a default.  (not a number) 
- Cecile spotted 2 things last week in participants.json and tsv :
a. in both participants.tsv and .json : Column order should be subproject then project (see loris-mri#558)
and 
b. in participants.json : for site, subproject and project the Description values should be: 
    "site": {
        "Description": "Site of the testing"
    },
    "subproject": {
        "Description": "Subproject of the participant"
    },
    "project": {
        "Description": "Project of the participant"
    },

**Comment by laemtl** [comment]
Solved in #37
