### ISSUE TITLE
Powerline Frequency cannot be left blank

### ISSUE THREAD

**Issue by jeffersoncasimir** [aces/EEG2BIDS#93]
If the `Powerline Frequency` is left to the default value of `'n/a'`, a TypeError is raised and not handled. I think instead of handling this error at runtime, it should be a requirement before allowing conversion.

**Comment by laemtl** [comment]
n/a is a valid value: 
<img width="704" alt="Screenshot 2023-07-18 at 4 25 34 PM" src="https://github.com/aces/EEG2BIDS/assets/32041423/02e961b1-31a2-4638-bd18-48c7cc460127">

**Comment by laemtl** [comment]
Fixed.
