### ISSUE TITLE
.SET files with continuous EEG cannot be imported 

### ISSUE THREAD

**Issue by oldgandalf** [aces/EEG2BIDS#95]
I tried and after specifying all parameters, when trying to convert to BIDS, it produced the following error:

Task error:
Unknown - only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by laemtl** [comment]
Hello @oldgandalf' can you share the dataset you used?

**Comment by oldgandalf** [comment]
[python.log](https://github.com/aces/EEG2BIDS/files/12094521/python.log)
[js.log](https://github.com/aces/EEG2BIDS/files/12094522/js.log)

@laemtl here my logs

**Comment by christinerogers** [comment]
@oldgandalf can you try again with any of your files that also have an .FDT file?

**Comment by laemtl** [comment]
This is fixed in the new release

**Comment by oldgandalf** [comment]
where is the new version @laemtl ?
