### ISSUE TITLE
critical bugs: OHBM windows .SET test(TIDCC file from HBCD)

### ISSUE THREAD

**Issue by christinerogers** [aces/EEG2BIDS#96]
Tested the set2bids.exe on Windows 11 on Laetitia's .SET test file 
screenshots available.

- can't scroll down to access last 2 tasks.  i think there's a frame size assumption? 
then and probably as a result: 
- operation did not complete. Error:  `Task Error "unknown - NoneType" object is not subscriptable`

caveats:
not tested on ieeg. 
not tested on epoched data

**Comment by christinerogers** [comment]
@laemtl i tested your file -- critical error here but may be very fixable.  could you give it a go? 
i can't scroll to the bottom so can't access the last 2 tasks
will send you video on slack

**Comment by laemtl** [comment]
Scroll issue fixed in next build.

**Comment by laemtl** [comment]
Should be fixed.
